// ═══════════════════════════════════════════
// KTMDrip — Static Product Data (Fallback)
// Used when D1 is not configured or for initial development
// ═══════════════════════════════════════════

import type { Product } from "./types";

const now = new Date().toISOString();

export const MEN_PRODUCTS: Product[] = [
  { id: 1,  name: "Oversized Graphic Tee",  slug: "oversized-graphic-tee",  description: "Bold streetwear essential with contemporary Kathmandu-inspired graphics.",  price: 2800, sale_price: null, discount: null, tag: "New",        category: "Tops",      gender: "men", image_url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=85", stock: 50, featured: 1, is_new: 1, created_at: now },
  { id: 2,  name: "Slim Fit Chinos",        slug: "slim-fit-chinos",        description: "Tailored slim-fit chinos in premium stretch cotton.",                        price: 3500, sale_price: null, discount: null, tag: "Popular",    category: "Bottoms",   gender: "men", image_url: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=85", stock: 50, featured: 1, is_new: 0, created_at: now },
  { id: 3,  name: "Bomber Jacket",          slug: "bomber-jacket",          description: "Classic bomber silhouette reimagined with modern proportions.",                price: 6800, sale_price: null, discount: null, tag: "Featured",   category: "Outerwear", gender: "men", image_url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=85", stock: 50, featured: 0, is_new: 1, created_at: now },
  { id: 4,  name: "Cargo Utility Pants",    slug: "cargo-utility-pants",    description: "Functional cargo pants with articulated knees and hidden zip pockets.",        price: 4200, sale_price: null, discount: null, tag: "New",        category: "Bottoms",   gender: "men", image_url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=85", stock: 50, featured: 0, is_new: 1, created_at: now },
  { id: 5,  name: "Ribbed Polo Shirt",      slug: "ribbed-polo-shirt",      description: "Textured ribbed polo in breathable pima cotton.",                              price: 2600, sale_price: null, discount: null, tag: "Bestseller", category: "Tops",      gender: "men", image_url: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 6,  name: "Raw Denim Jacket",       slug: "raw-denim-jacket",       description: "Japanese selvedge raw denim jacket. Ages beautifully.",                        price: 5500, sale_price: null, discount: null, tag: "New",        category: "Outerwear", gender: "men", image_url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 7,  name: "Linen Summer Shirt",     slug: "linen-summer-shirt",     description: "Relaxed-fit linen shirt for warm Kathmandu days.",                             price: 3200, sale_price: null, discount: null, tag: "Seasonal",   category: "Tops",      gender: "men", image_url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 8,  name: "Athletic Joggers",       slug: "athletic-joggers",       description: "Technical joggers with tapered fit and moisture-wicking fabric.",               price: 3000, sale_price: null, discount: null, tag: "Comfort",    category: "Bottoms",   gender: "men", image_url: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 9,  name: "Merino Knit Sweater",    slug: "merino-knit-sweater",    description: "Luxurious merino wool knit sweater. Lightweight warmth.",                       price: 4800, sale_price: null, discount: null, tag: "Premium",    category: "Tops",      gender: "men", image_url: "https://images.unsplash.com/photo-1516826957135-700dedea698c?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 10, name: "Classic Trench Coat",    slug: "classic-trench-coat",    description: "Timeless trench coat with modern proportions.",                                  price: 8500, sale_price: null, discount: null, tag: "Signature",  category: "Outerwear", gender: "men", image_url: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
];

export const WOMEN_PRODUCTS: Product[] = [
  { id: 11, name: "Wrap Midi Dress",          slug: "wrap-midi-dress",          description: "Flattering wrap silhouette in flowing crepe fabric.",              price: 4500, sale_price: null, discount: null, tag: "Bestseller", category: "Dresses",   gender: "women", image_url: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=85", stock: 50, featured: 1, is_new: 0, created_at: now },
  { id: 12, name: "Linen Wide-Leg Trousers",  slug: "linen-wide-leg-trousers",  description: "Relaxed wide-leg trousers in premium European linen.",            price: 4500, sale_price: null, discount: null, tag: "Popular",    category: "Bottoms",   gender: "women", image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=85", stock: 50, featured: 1, is_new: 0, created_at: now },
  { id: 13, name: "Structured Blazer",        slug: "structured-blazer",        description: "Power blazer with structured shoulders and nipped waist.",         price: 7200, sale_price: null, discount: null, tag: "Featured",   category: "Outerwear", gender: "women", image_url: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=85", stock: 50, featured: 0, is_new: 1, created_at: now },
  { id: 14, name: "Ribbed Knit Cardigan",     slug: "ribbed-knit-cardigan",     description: "Oversized ribbed cardigan in chunky merino blend.",                price: 3900, sale_price: null, discount: null, tag: "Cozy",       category: "Tops",      gender: "women", image_url: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 15, name: "Silk Slip Dress",          slug: "silk-slip-dress",          description: "Luxurious silk charmeuse slip dress. Minimalist elegance.",        price: 5200, sale_price: null, discount: null, tag: "New",        category: "Dresses",   gender: "women", image_url: "https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=600&q=85", stock: 50, featured: 0, is_new: 1, created_at: now },
  { id: 16, name: "Cropped Leather Jacket",   slug: "cropped-leather-jacket",   description: "Butter-soft leather in a cropped moto silhouette.",               price: 8900, sale_price: null, discount: null, tag: "Signature",  category: "Outerwear", gender: "women", image_url: "https://images.unsplash.com/photo-1548549557-dbe9946621da?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 17, name: "Flowy Maxi Skirt",         slug: "flowy-maxi-skirt",         description: "Ethereal maxi skirt in printed georgette.",                        price: 3600, sale_price: null, discount: null, tag: "New",        category: "Bottoms",   gender: "women", image_url: "https://images.unsplash.com/photo-1583496661160-fb5974ca5176?w=600&q=85", stock: 50, featured: 0, is_new: 1, created_at: now },
  { id: 18, name: "Off-Shoulder Top",         slug: "off-shoulder-top",         description: "Romantic off-shoulder top in cotton poplin.",                       price: 2800, sale_price: null, discount: null, tag: "Summer",     category: "Tops",      gender: "women", image_url: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 19, name: "Tailored Bermuda Shorts",  slug: "tailored-bermuda-shorts",  description: "Polished bermuda shorts with pressed crease.",                     price: 2900, sale_price: null, discount: null, tag: "Casual",     category: "Bottoms",   gender: "women", image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
  { id: 20, name: "Belted Trench Coat",       slug: "belted-trench-coat",       description: "Classic trench reimagined with statement belt.",                    price: 8200, sale_price: null, discount: null, tag: "Premium",    category: "Outerwear", gender: "women", image_url: "https://images.unsplash.com/photo-1554568218-0f1715e72254?w=600&q=85", stock: 50, featured: 0, is_new: 0, created_at: now },
];

export const SALE_PRODUCTS: Product[] = [
  { id: 21, name: "Bomber Jacket",           slug: "bomber-jacket-sale",          description: "Classic bomber silhouette — now at an incredible price.",       price: 6800, sale_price: 4599, discount: 32, tag: "Sale", category: "Outerwear", gender: "men",   image_url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=85", stock: 15, featured: 0, is_new: 0, created_at: now },
  { id: 22, name: "Merino Knit Sweater",     slug: "merino-knit-sweater-sale",    description: "Luxurious merino wool knit — limited time offer.",              price: 4800, sale_price: 3199, discount: 33, tag: "Sale", category: "Tops",      gender: "men",   image_url: "https://images.unsplash.com/photo-1516826957135-700dedea698c?w=600&q=85", stock: 10, featured: 0, is_new: 0, created_at: now },
  { id: 23, name: "Cargo Utility Pants",     slug: "cargo-utility-pants-sale",    description: "Functional cargo pants — grab them before they go.",            price: 4200, sale_price: 2799, discount: 33, tag: "Sale", category: "Bottoms",   gender: "men",   image_url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=85", stock: 8,  featured: 0, is_new: 0, created_at: now },
  { id: 24, name: "Slim Fit Chinos",         slug: "slim-fit-chinos-sale",        description: "Premium stretch cotton chinos at a steal.",                     price: 3500, sale_price: 2299, discount: 34, tag: "Sale", category: "Bottoms",   gender: "men",   image_url: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=85", stock: 12, featured: 0, is_new: 0, created_at: now },
  { id: 25, name: "Raw Denim Jacket",        slug: "raw-denim-jacket-sale",       description: "Japanese selvedge raw denim — don't miss this deal.",           price: 5500, sale_price: 3499, discount: 36, tag: "Sale", category: "Outerwear", gender: "men",   image_url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=85", stock: 5,  featured: 0, is_new: 0, created_at: now },
  { id: 26, name: "Structured Blazer",       slug: "structured-blazer-sale",      description: "Power blazer at an unbeatable price.",                          price: 7200, sale_price: 4799, discount: 33, tag: "Sale", category: "Outerwear", gender: "women", image_url: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=85", stock: 7,  featured: 0, is_new: 0, created_at: now },
  { id: 27, name: "Cropped Leather Jacket",  slug: "cropped-leather-jacket-sale", description: "Butter-soft leather moto jacket — limited stock.",              price: 8900, sale_price: 5899, discount: 34, tag: "Sale", category: "Outerwear", gender: "women", image_url: "https://images.unsplash.com/photo-1548549557-dbe9946621da?w=600&q=85", stock: 3,  featured: 0, is_new: 0, created_at: now },
  { id: 28, name: "Flowy Maxi Skirt",        slug: "flowy-maxi-skirt-sale",       description: "Ethereal maxi skirt — summer sale special.",                    price: 3600, sale_price: 2299, discount: 36, tag: "Sale", category: "Bottoms",   gender: "women", image_url: "https://images.unsplash.com/photo-1583496661160-fb5974ca5176?w=600&q=85", stock: 9,  featured: 0, is_new: 0, created_at: now },
  { id: 29, name: "Wrap Midi Dress",         slug: "wrap-midi-dress-sale",        description: "Bestselling wrap dress at a special price.",                     price: 4500, sale_price: 2899, discount: 36, tag: "Sale", category: "Dresses",   gender: "women", image_url: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&q=85", stock: 11, featured: 0, is_new: 0, created_at: now },
  { id: 30, name: "Silk Slip Dress",         slug: "silk-slip-dress-sale",        description: "Luxurious silk charmeuse — biggest discount of the season.",     price: 5200, sale_price: 3299, discount: 37, tag: "Sale", category: "Dresses",   gender: "women", image_url: "https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=600&q=85", stock: 6,  featured: 0, is_new: 0, created_at: now },
  { id: 31, name: "Classic Trench Coat",     slug: "classic-trench-coat-sale",    description: "Timeless trench coat — end of season clearance.",                price: 8500, sale_price: 5499, discount: 35, tag: "Sale", category: "Outerwear", gender: "men",   image_url: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&q=85", stock: 4,  featured: 0, is_new: 0, created_at: now },
  { id: 32, name: "Belted Trench Coat",      slug: "belted-trench-coat-sale",     description: "Classic trench reimagined — biggest savings here.",              price: 8200, sale_price: 5199, discount: 37, tag: "Sale", category: "Outerwear", gender: "women", image_url: "https://images.unsplash.com/photo-1554568218-0f1715e72254?w=600&q=85", stock: 4,  featured: 0, is_new: 0, created_at: now },
];

export const ALL_PRODUCTS: Product[] = [...MEN_PRODUCTS, ...WOMEN_PRODUCTS, ...SALE_PRODUCTS];
